### ISSUE TITLE
OVO API official documentation?

### ISSUE THREAD

**Issue by sarahsau** [namdevel/ovoid-ruby#1]
Halo @namdevel, terimakasih banyak sudah membuat Ruby wrapper untuk OVO. Pas banget saya sedang mencari cara untuk integrasi membaca transaksi OVO untuk aplikasi Rails. 

Izin bertanya, untuk OVOid API sendiri, dokumentasi resminya dimana ya? Saya Googling gak nemu. Apa memang OVO ini API nya private ya?

Terimakasih bantuannya.

**Comment by namtxs** [comment]
untuk official docs nya tidak ada kak

**Comment by sarahsau** [comment]
Oh begitu ya, terimakasih konfirmasinya.

**Comment by sarahsau** [comment]
@namdevel, di Step 3,  yang `securityCode` itu valuenya dapat dari mana yah? 

```
AuthToken = ovo.loginSecurityCode('<securityCode>', '<updateAccessToken>')
```
Terimakasih bantuannya.
